# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'security_user.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 591)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 70, 661, 461))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(20, 20, 201, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_11 = QtGui.QWidget()
        self.tab_11.setObjectName(_fromUtf8("tab_11"))
        self.graphicsView_2 = QtGui.QGraphicsView(self.tab_11)
        self.graphicsView_2.setGeometry(QtCore.QRect(10, 50, 141, 91))
        self.graphicsView_2.setObjectName(_fromUtf8("graphicsView_2"))
        self.label_2 = QtGui.QLabel(self.tab_11)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 101, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.graphicsView_3 = QtGui.QGraphicsView(self.tab_11)
        self.graphicsView_3.setGeometry(QtCore.QRect(160, 50, 141, 91))
        self.graphicsView_3.setObjectName(_fromUtf8("graphicsView_3"))
        self.graphicsView_4 = QtGui.QGraphicsView(self.tab_11)
        self.graphicsView_4.setGeometry(QtCore.QRect(310, 50, 141, 91))
        self.graphicsView_4.setObjectName(_fromUtf8("graphicsView_4"))
        self.graphicsView_5 = QtGui.QGraphicsView(self.tab_11)
        self.graphicsView_5.setGeometry(QtCore.QRect(460, 50, 141, 91))
        self.graphicsView_5.setObjectName(_fromUtf8("graphicsView_5"))
        self.graphicsView_6 = QtGui.QGraphicsView(self.tab_11)
        self.graphicsView_6.setGeometry(QtCore.QRect(310, 230, 141, 91))
        self.graphicsView_6.setObjectName(_fromUtf8("graphicsView_6"))
        self.graphicsView_7 = QtGui.QGraphicsView(self.tab_11)
        self.graphicsView_7.setGeometry(QtCore.QRect(10, 230, 141, 91))
        self.graphicsView_7.setObjectName(_fromUtf8("graphicsView_7"))
        self.graphicsView_8 = QtGui.QGraphicsView(self.tab_11)
        self.graphicsView_8.setGeometry(QtCore.QRect(460, 230, 141, 91))
        self.graphicsView_8.setObjectName(_fromUtf8("graphicsView_8"))
        self.graphicsView_9 = QtGui.QGraphicsView(self.tab_11)
        self.graphicsView_9.setGeometry(QtCore.QRect(160, 230, 141, 91))
        self.graphicsView_9.setObjectName(_fromUtf8("graphicsView_9"))
        self.label_3 = QtGui.QLabel(self.tab_11)
        self.label_3.setGeometry(QtCore.QRect(10, 150, 46, 13))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_6 = QtGui.QLabel(self.tab_11)
        self.label_6.setGeometry(QtCore.QRect(160, 150, 71, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.tab_11)
        self.label_7.setGeometry(QtCore.QRect(310, 150, 71, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_9 = QtGui.QLabel(self.tab_11)
        self.label_9.setGeometry(QtCore.QRect(460, 150, 101, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.tab_11)
        self.label_10.setGeometry(QtCore.QRect(10, 330, 81, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.tab_11)
        self.label_11.setGeometry(QtCore.QRect(160, 330, 91, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.tab_11)
        self.label_12.setGeometry(QtCore.QRect(310, 330, 61, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.tab_11)
        self.label_13.setGeometry(QtCore.QRect(470, 330, 101, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.tabWidget.addTab(self.tab_11, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.graphicsView_10 = QtGui.QGraphicsView(self.tab_2)
        self.graphicsView_10.setGeometry(QtCore.QRect(10, 10, 441, 421))
        self.graphicsView_10.setObjectName(_fromUtf8("graphicsView_10"))
        self.listView = QtGui.QListView(self.tab_2)
        self.listView.setGeometry(QtCore.QRect(470, 10, 171, 421))
        self.listView.setObjectName(_fromUtf8("listView"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.label_8 = QtGui.QLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 131, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.tabWidget_2 = QtGui.QTabWidget(self.tab_3)
        self.tabWidget_2.setGeometry(QtCore.QRect(10, 40, 631, 401))
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.tabWidget_2.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.tabWidget_2.addTab(self.tab_6, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.tabWidget_2.addTab(self.tab_7, _fromUtf8(""))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.tabWidget_2.addTab(self.tab_8, _fromUtf8(""))
        self.tab_9 = QtGui.QWidget()
        self.tab_9.setObjectName(_fromUtf8("tab_9"))
        self.tabWidget_2.addTab(self.tab_9, _fromUtf8(""))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.comboBox = QtGui.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(680, 90, 111, 22))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox_2 = QtGui.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(678, 270, 111, 22))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_3 = QtGui.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(680, 430, 111, 22))
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.graphicsView = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(10, 10, 661, 51))
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "Welcome, <insert name> !", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Home", None))
        self.label_2.setText(_translate("MainWindow", "Security Cameras", None))
        self.label_3.setText(_translate("MainWindow", "Entrance", None))
        self.label_6.setText(_translate("MainWindow", "Main Lobby", None))
        self.label_7.setText(_translate("MainWindow", "Workstation 1", None))
        self.label_9.setText(_translate("MainWindow", "Workstation 2", None))
        self.label_10.setText(_translate("MainWindow", "Workstation 3", None))
        self.label_11.setText(_translate("MainWindow", "Workstation 4", None))
        self.label_12.setText(_translate("MainWindow", "Canteen", None))
        self.label_13.setText(_translate("MainWindow", "Backdoor Entrance", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_11), _translate("MainWindow", "Security Cameras", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tracking", None))
        self.label_8.setText(_translate("MainWindow", "Account: Health Monitor", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "Home", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "Cardiovascular", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("MainWindow", "Blood Test", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("MainWindow", "BMI", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_9), _translate("MainWindow", "Other", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Account", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "CV", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "Interview", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "Blank pa", None))
        self.comboBox.setItemText(3, _translate("MainWindow", "Blank pa", None))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Health Monitor", None))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Performance Shit", None))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "blank pa", None))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "blank pa", None))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "logout", None))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "HR", None))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "IT", None))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "Sales", None))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "etc", None))

